import type {
  Category,
  Offer,
  Order,
  Product,
  ProductVariant,
  Testimonial,
  User,
} from './types'

const img = (name: string) => `/images/products/${name}.png`

function variants(
  id: string,
  options: Array<[label: string, grams: number, price: number, mrp?: number]>,
): ProductVariant[] {
  return options.map(([label, grams, price, mrp]) => ({
    id: `${id}-${grams}`,
    label,
    grams,
    price,
    mrp: mrp ?? price,
  }))
}

export const categories: Category[] = [
  {
    slug: 'cakes',
    name: 'Cakes',
    description: 'Layered, frosted and celebration-ready',
    image: img('chocolate-truffle-cake'),
  },
  {
    slug: 'pastries',
    name: 'Pastries',
    description: 'Laminated, flaky and buttery',
    image: img('butter-croissant'),
  },
  {
    slug: 'breads',
    name: 'Breads',
    description: 'Slow-fermented loaves baked daily',
    image: img('sourdough-loaf'),
  },
  {
    slug: 'cookies',
    name: 'Cookies',
    description: 'Crisp edges, soft centres',
    image: img('choco-chip-cookies'),
  },
  {
    slug: 'cupcakes',
    name: 'Cupcakes',
    description: 'Single-serve treats for any day',
    image: img('vanilla-cupcakes'),
  },
  {
    slug: 'savouries',
    name: 'Savouries',
    description: 'Puffs and bakes for tea time',
    image: img('veg-puff'),
  },
]

export const products: Product[] = [
  {
    id: 'p1',
    slug: 'chocolate-truffle-cake',
    name: 'Chocolate Truffle Cake',
    category: 'cakes',
    description:
      'Moist dark chocolate sponge layered with silky Belgian chocolate ganache and finished with hand-shaved chocolate curls.',
    image: img('chocolate-truffle-cake'),
    variants: variants('p1', [
      ['500 g', 500, 649, 749],
      ['1 kg', 1000, 1199, 1399],
      ['2 kg', 2000, 2299, 2699],
    ]),
    rating: 4.8,
    reviewCount: 214,
    isVeg: true,
    availability: 'AVAILABLE_NOW',
    tags: ['bestseller'],
    ingredients: ['Belgian dark chocolate', 'Fresh cream', 'Refined flour', 'Cocoa', 'Sugar'],
    allergens: ['Gluten', 'Dairy'],
    shelfLife: 'Best consumed within 2 days. Keep refrigerated.',
    reviews: [
      { id: 'r1', author: 'Ananya R.', rating: 5, comment: 'Rich without being too sweet. Ordered for a birthday and everyone asked where it was from.', date: '2026-09-12' },
      { id: 'r2', author: 'Karthik S.', rating: 5, comment: 'The ganache is perfect. Delivery was on time too.', date: '2026-09-02' },
      { id: 'r3', author: 'Meera P.', rating: 4, comment: 'Lovely cake, would like a slightly lighter sponge next time.', date: '2026-08-21' },
    ],
  },
  {
    id: 'p2',
    slug: 'red-velvet-cake',
    name: 'Red Velvet Cake',
    category: 'cakes',
    description:
      'Velvety buttermilk sponge with a hint of cocoa, layered with tangy cream cheese frosting.',
    image: img('red-velvet-cake'),
    variants: variants('p2', [
      ['500 g', 500, 699],
      ['1 kg', 1000, 1299],
    ]),
    rating: 4.7,
    reviewCount: 168,
    isVeg: false,
    availability: 'READY_IN_TIME',
    readyInMinutes: 120,
    tags: ['bestseller'],
    ingredients: ['Buttermilk', 'Cream cheese', 'Eggs', 'Cocoa', 'Refined flour'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    shelfLife: 'Best consumed within 2 days. Keep refrigerated.',
    reviews: [
      { id: 'r4', author: 'Rohan D.', rating: 5, comment: 'The cream cheese frosting is spot on.', date: '2026-09-18' },
    ],
  },
  {
    id: 'p3',
    slug: 'blueberry-cheesecake',
    name: 'Blueberry Cheesecake',
    category: 'cakes',
    description:
      'Baked New York–style cheesecake on a buttery biscuit base, topped with house-made blueberry compote.',
    image: img('blueberry-cheesecake'),
    variants: variants('p3', [
      ['500 g', 500, 849, 949],
      ['1 kg', 1000, 1599, 1799],
    ]),
    rating: 4.9,
    reviewCount: 97,
    isVeg: false,
    availability: 'PRE_ORDER',
    preOrderHours: 24,
    tags: ['special'],
    ingredients: ['Cream cheese', 'Blueberries', 'Eggs', 'Digestive biscuits', 'Butter'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    shelfLife: 'Best consumed within 3 days. Keep refrigerated.',
    reviews: [
      { id: 'r5', author: 'Sneha K.', rating: 5, comment: 'Creamy, dense and not overly sweet. Worth the pre-order wait.', date: '2026-09-10' },
    ],
  },
  {
    id: 'p4',
    slug: 'black-forest-cake',
    name: 'Black Forest Cake',
    category: 'cakes',
    description:
      'Chocolate sponge soaked in cherry syrup, layered with whipped cream and dark cherries.',
    image: img('black-forest-cake'),
    variants: variants('p4', [
      ['500 g', 500, 549],
      ['1 kg', 1000, 999],
    ]),
    rating: 4.6,
    reviewCount: 241,
    isVeg: true,
    availability: 'SOLD_OUT',
    tags: ['bestseller'],
    ingredients: ['Cocoa sponge', 'Whipped cream', 'Cherries', 'Chocolate shavings'],
    allergens: ['Gluten', 'Dairy'],
    shelfLife: 'Best consumed within 2 days. Keep refrigerated.',
    reviews: [],
  },
  {
    id: 'p5',
    slug: 'butter-croissant',
    name: 'Butter Croissant',
    category: 'pastries',
    description:
      'Hand-laminated over three days with cultured butter for a crisp shell and honeycomb crumb.',
    image: img('butter-croissant'),
    variants: variants('p5', [
      ['1 pc (80 g)', 80, 110],
      ['Box of 4 (320 g)', 320, 399, 440],
    ]),
    rating: 4.8,
    reviewCount: 312,
    isVeg: false,
    availability: 'AVAILABLE_NOW',
    tags: ['bestseller', 'fresh'],
    ingredients: ['Cultured butter', 'Flour', 'Milk', 'Eggs', 'Yeast'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    shelfLife: 'Best on the day of baking. Warm for 3 minutes to refresh.',
    reviews: [
      { id: 'r6', author: 'Arjun M.', rating: 5, comment: 'Genuinely flaky. Best croissant I have had in the city.', date: '2026-09-20' },
    ],
  },
  {
    id: 'p6',
    slug: 'cinnamon-roll',
    name: 'Cinnamon Roll',
    category: 'pastries',
    description:
      'Soft brioche swirled with cinnamon brown sugar and finished with a vanilla glaze.',
    image: img('cinnamon-roll'),
    variants: variants('p6', [
      ['1 pc (120 g)', 120, 140],
      ['Box of 6 (720 g)', 720, 749, 840],
    ]),
    rating: 4.7,
    reviewCount: 129,
    isVeg: false,
    availability: 'AVAILABLE_NOW',
    tags: ['fresh', 'special'],
    ingredients: ['Brioche dough', 'Cinnamon', 'Brown sugar', 'Butter', 'Icing sugar'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    shelfLife: 'Best within 24 hours.',
    reviews: [],
  },
  {
    id: 'p7',
    slug: 'fruit-danish',
    name: 'Fresh Fruit Danish',
    category: 'pastries',
    description:
      'Buttery Danish pastry filled with vanilla custard and topped with seasonal berries.',
    image: img('fruit-danish'),
    variants: variants('p7', [
      ['1 pc (100 g)', 100, 150],
      ['Box of 4 (400 g)', 400, 549, 600],
    ]),
    rating: 4.5,
    reviewCount: 64,
    isVeg: false,
    availability: 'READY_IN_TIME',
    readyInMinutes: 90,
    tags: ['special'],
    ingredients: ['Danish dough', 'Custard', 'Strawberries', 'Blueberries'],
    allergens: ['Gluten', 'Dairy', 'Egg'],
    shelfLife: 'Best on the day of baking. Keep refrigerated.',
    reviews: [],
  },
  {
    id: 'p8',
    slug: 'classic-sourdough',
    name: 'Classic Sourdough Loaf',
    category: 'breads',
    description:
      'Naturally leavened with our 6-year-old starter and fermented for 36 hours for a tangy, open crumb.',
    image: img('sourdough-loaf'),
    variants: variants('p8', [
      ['Half loaf (400 g)', 400, 180],
      ['Full loaf (800 g)', 800, 320],
    ]),
    rating: 4.9,
    reviewCount: 188,
    isVeg: true,
    availability: 'AVAILABLE_NOW',
    tags: ['bestseller', 'fresh'],
    ingredients: ['Unbleached flour', 'Whole wheat', 'Water', 'Sea salt', 'Wild yeast starter'],
    allergens: ['Gluten'],
    shelfLife: 'Stays fresh for 3 days at room temperature.',
    reviews: [
      { id: 'r7', author: 'Divya N.', rating: 5, comment: 'Crust crackles, crumb is perfect. Our weekly staple now.', date: '2026-09-15' },
    ],
  },
  {
    id: 'p9',
    slug: 'multigrain-bread',
    name: 'Multigrain Sandwich Bread',
    category: 'breads',
    description:
      'Soft sandwich loaf packed with oats, flax, sunflower and pumpkin seeds.',
    image: img('multigrain-bread'),
    variants: variants('p9', [['1 loaf (450 g)', 450, 120]]),
    rating: 4.6,
    reviewCount: 142,
    isVeg: true,
    availability: 'AVAILABLE_NOW',
    tags: ['fresh'],
    ingredients: ['Whole wheat', 'Oats', 'Flax', 'Sunflower seeds', 'Pumpkin seeds'],
    allergens: ['Gluten'],
    shelfLife: 'Stays fresh for 3 days at room temperature.',
    reviews: [],
  },
  {
    id: 'p10',
    slug: 'garlic-rosemary-focaccia',
    name: 'Garlic Rosemary Focaccia',
    category: 'breads',
    description:
      'Airy olive-oil focaccia topped with roasted garlic, fresh rosemary and flaky salt.',
    image: img('garlic-focaccia'),
    variants: variants('p10', [['Tray (500 g)', 500, 260, 290]]),
    rating: 4.7,
    reviewCount: 58,
    isVeg: true,
    availability: 'READY_IN_TIME',
    readyInMinutes: 60,
    tags: ['special'],
    ingredients: ['Flour', 'Extra virgin olive oil', 'Garlic', 'Rosemary', 'Sea salt'],
    allergens: ['Gluten'],
    shelfLife: 'Best within 24 hours.',
    reviews: [],
  },
  {
    id: 'p11',
    slug: 'choco-chip-cookies',
    name: 'Chocolate Chip Cookies',
    category: 'cookies',
    description:
      'Brown-butter cookies loaded with dark chocolate chunks and a sprinkle of sea salt.',
    image: img('choco-chip-cookies'),
    variants: variants('p11', [
      ['Pack of 6 (240 g)', 240, 299, 330],
      ['Pack of 12 (480 g)', 480, 549, 660],
    ]),
    rating: 4.8,
    reviewCount: 276,
    isVeg: true,
    availability: 'AVAILABLE_NOW',
    tags: ['bestseller'],
    ingredients: ['Brown butter', 'Dark chocolate', 'Flour', 'Brown sugar', 'Sea salt'],
    allergens: ['Gluten', 'Dairy'],
    shelfLife: 'Stays fresh for 7 days in an airtight container.',
    reviews: [],
  },
  {
    id: 'p12',
    slug: 'almond-biscotti',
    name: 'Almond Biscotti',
    category: 'cookies',
    description:
      'Twice-baked Italian biscotti with toasted almonds and orange zest. Perfect with coffee.',
    image: img('almond-biscotti'),
    variants: variants('p12', [['Jar (200 g)', 200, 249]]),
    rating: 4.4,
    reviewCount: 41,
    isVeg: true,
    availability: 'PRE_ORDER',
    preOrderHours: 12,
    tags: [],
    ingredients: ['Almonds', 'Flour', 'Sugar', 'Orange zest'],
    allergens: ['Gluten', 'Tree nuts'],
    shelfLife: 'Stays fresh for 3 weeks in an airtight container.',
    reviews: [],
  },
  {
    id: 'p13',
    slug: 'vanilla-cupcakes',
    name: 'Vanilla Bean Cupcakes',
    category: 'cupcakes',
    description:
      'Light vanilla bean sponge topped with a swirl of whipped buttercream.',
    image: img('vanilla-cupcakes'),
    variants: variants('p13', [
      ['Box of 4 (280 g)', 280, 320],
      ['Box of 12 (840 g)', 840, 899, 960],
    ]),
    rating: 4.6,
    reviewCount: 88,
    isVeg: true,
    availability: 'AVAILABLE_NOW',
    tags: ['fresh'],
    ingredients: ['Vanilla bean', 'Butter', 'Flour', 'Sugar', 'Milk'],
    allergens: ['Gluten', 'Dairy'],
    shelfLife: 'Best within 2 days. Keep refrigerated in warm weather.',
    reviews: [],
  },
  {
    id: 'p14',
    slug: 'veg-puff',
    name: 'Classic Veg Puff',
    category: 'savouries',
    description:
      'Flaky puff pastry filled with a spiced potato, pea and carrot masala.',
    image: img('veg-puff'),
    variants: variants('p14', [
      ['1 pc (90 g)', 90, 40],
      ['Box of 6 (540 g)', 540, 220, 240],
    ]),
    rating: 4.5,
    reviewCount: 305,
    isVeg: true,
    availability: 'AVAILABLE_NOW',
    tags: ['fresh', 'bestseller'],
    ingredients: ['Puff pastry', 'Potato', 'Peas', 'Carrot', 'Spices'],
    allergens: ['Gluten', 'Dairy'],
    shelfLife: 'Best warm, on the day of baking.',
    reviews: [],
  },
  {
    id: 'p15',
    slug: 'chicken-puff',
    name: 'Spiced Chicken Puff',
    category: 'savouries',
    description:
      'Golden puff pastry with a peppery chicken and onion filling.',
    image: img('chicken-puff'),
    variants: variants('p15', [
      ['1 pc (100 g)', 100, 60],
      ['Box of 6 (600 g)', 600, 330, 360],
    ]),
    rating: 4.6,
    reviewCount: 196,
    isVeg: false,
    availability: 'SOLD_OUT',
    tags: ['fresh'],
    ingredients: ['Puff pastry', 'Chicken', 'Onion', 'Black pepper', 'Spices'],
    allergens: ['Gluten', 'Dairy'],
    shelfLife: 'Best warm, on the day of baking.',
    reviews: [],
  },
]

export const offers: Offer[] = [
  {
    code: 'FRESH10',
    title: '10% off your order',
    description: 'On orders above ₹499. Valid on all products.',
    discountType: 'percent',
    value: 10,
    minOrder: 499,
  },
  {
    code: 'CAKE150',
    title: '₹150 off on cakes',
    description: 'Flat discount on orders above ₹1,200.',
    discountType: 'flat',
    value: 150,
    minOrder: 1200,
  },
  {
    code: 'FREEDEL',
    title: 'Free delivery',
    description: 'No delivery charge on orders above ₹299.',
    discountType: 'free-delivery',
    value: 0,
    minOrder: 299,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Priya Venkatesh',
    location: 'Indiranagar',
    rating: 5,
    comment:
      'They made our daughter’s unicorn cake exactly as we described. It tasted as good as it looked, and the team kept us updated on WhatsApp.',
  },
  {
    id: 't2',
    name: 'Rahul Iyer',
    location: 'Koramangala',
    rating: 5,
    comment:
      'Their sourdough is the real deal. I pre-order every Friday and pick it up warm on Saturday morning.',
  },
  {
    id: 't3',
    name: 'Fatima Sheikh',
    location: 'HSR Layout',
    rating: 4,
    comment:
      'Lovely eggless options that do not compromise on taste. Delivery slots are convenient for office orders.',
  },
]

export const seedUser: User & { password: string } = {
  id: 'u-demo',
  name: 'Demo Customer',
  email: 'demo@bluebellbakehouse.in',
  password: 'demo1234',
  phone: '9876500000',
  addresses: [
    {
      id: 'a1',
      label: 'Home',
      line1: '18, 4th Cross, HAL 2nd Stage',
      line2: 'Near Metro Station',
      city: 'Bengaluru',
      pincode: '560008',
      phone: '9876500000',
    },
  ],
}

export const seedOrders: Order[] = [
  {
    id: 'BB-10241',
    userId: 'u-demo',
    customerName: 'Demo Customer',
    phone: '9876500000',
    lines: [
      {
        productId: 'p1',
        name: 'Chocolate Truffle Cake',
        image: img('chocolate-truffle-cake'),
        variantLabel: '1 kg',
        unitPrice: 1199,
        quantity: 1,
      },
      {
        productId: 'p5',
        name: 'Butter Croissant',
        image: img('butter-croissant'),
        variantLabel: 'Box of 4 (320 g)',
        unitPrice: 399,
        quantity: 1,
      },
    ],
    subtotal: 1598,
    discount: 160,
    deliveryFee: 0,
    total: 1438,
    couponCode: 'FRESH10',
    fulfilment: 'delivery',
    address: {
      label: 'Home',
      line1: '18, 4th Cross, HAL 2nd Stage',
      city: 'Bengaluru',
      pincode: '560008',
      phone: '9876500000',
    },
    scheduledDate: '2026-09-14',
    timeSlot: '5:00 PM – 7:00 PM',
    payment: 'online',
    paymentStatus: 'PAID',
    status: 'COMPLETED',
    createdAt: '2026-09-13T10:12:00.000Z',
    statusHistory: [
      { status: 'PLACED', at: '2026-09-13T10:12:00.000Z' },
      { status: 'CONFIRMED', at: '2026-09-13T10:20:00.000Z' },
      { status: 'BAKING', at: '2026-09-14T08:30:00.000Z' },
      { status: 'OUT_FOR_DELIVERY', at: '2026-09-14T11:40:00.000Z' },
      { status: 'COMPLETED', at: '2026-09-14T12:15:00.000Z' },
    ],
  },
]
